parameters:
#    lunchy_web.example.class: Lunchy\Bundle\WebBundle\Example

services:
#    lunchy_web.example:
#        class: %lunchy_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
